import { createSign, generateKeyPairSync } from 'node:crypto';

/**
 * ZATCA EGS CSR generator — secp256k1 keypair + PKCS#10 CSR carrying the
 * nine EGS fields from the SDK's csr-config template (docs/10 §Keys & CSR).
 *
 * The DER is hand-rolled on node:crypto (project rule: no new npm deps —
 * same reason scrypt auth was built on node:crypto). The layout is locked
 * byte-for-byte against a CSR generated by ZATCA's own SDK CLI and decoded
 * with `openssl asn1parse`:
 *
 *   Subject (this exact order): C (PrintableString), OU, O, CN (UTF8String)
 *   Requested extensions:
 *     1.3.6.1.4.1.311.20.2 (MS certificateTemplateName)
 *         = UTF8String, environment-dependent (TST/PRE/plain prefix)
 *     subjectAltName = dirName with one RDN per attribute, in order:
 *         SN, UID, title, registeredAddress, businessCategory
 *   Signature: ecdsa-with-SHA256 over the CertificationRequestInfo
 *
 * TRAP (verified against the SDK's output): openssl's `SN` short name is
 * SURNAME (2.5.4.4), NOT serialNumber (2.5.4.5). ZATCA's tooling inherits
 * that, so the EGS serial '1-X|2-X|3-<uuid>' lives in the surname
 * attribute. Using 2.5.4.5 produces a CSR the portal rejects.
 */
export interface CsrConfig {
  commonName: string;
  /** EGS unit serial, format '1-<solution>|2-<model>|3-<uuid>'. */
  serialNumber: string;
  /** 15-digit VAT registration number; must start AND end with 3. */
  organizationIdentifier: string;
  organizationUnitName: string;
  organizationName: string;
  /** ISO 3166-1 alpha-2, 'SA' for us. */
  countryName: string;
  /**
   * Force the VAT-GROUP rule on (organizationUnitName must be the
   * member's 10-digit TIN). Normally unnecessary: a VAT number whose
   * 11th digit is '1' is detected as a group registration automatically.
   * This only ADDS to that detection, never disables it.
   */
  vatGroup?: boolean;
  /**
   * Functionality map over 'TSCZ', 1 = supported: '0100' = simplified-only
   * B2C till, '1100' = standard + simplified. Cannot be all zeros.
   */
  invoiceType: string;
  /** Branch/EGS-unit address (a website is allowed for e-commerce). */
  locationAddress: string;
  industryBusinessCategory: string;
}

export type ZatcaEnvironment = 'sandbox' | 'simulation' | 'production';

/**
 * The certificateTemplateName the portal expects per environment — a wrong
 * name is a rejected CSR (docs/06 refs; cross-checked salla-zatca +
 * zatca-xml-js).
 */
export const CERTIFICATE_TEMPLATE_BY_ENV: Record<ZatcaEnvironment, string> = {
  sandbox: 'TSTZATCA-Code-Signing',
  simulation: 'PREZATCA-Code-Signing',
  production: 'ZATCA-Code-Signing',
};

export interface GeneratedCsr {
  csrPem: string;
  /** base64 of the PEM — the exact `csr` body POST /compliance wants. */
  csrBase64: string;
  privateKeyPem: string;
  publicKeyPem: string;
}

export class CsrConfigError extends Error {}

const OID = {
  commonName: '2.5.4.3',
  surname: '2.5.4.4', // openssl 'SN' — carries the EGS serial (see header)
  countryName: '2.5.4.6',
  organizationName: '2.5.4.10',
  organizationalUnitName: '2.5.4.11',
  title: '2.5.4.12',
  businessCategory: '2.5.4.15',
  registeredAddress: '2.5.4.26',
  uid: '0.9.2342.19200300.100.1.1',
  extensionRequest: '1.2.840.113549.1.9.14',
  certificateTemplateName: '1.3.6.1.4.1.311.20.2',
  subjectAltName: '2.5.29.17',
  ecdsaWithSha256: '1.2.840.10045.4.3.2',
};

// ---- minimal DER writers ---------------------------------------------------

function derLength(n: number): Buffer {
  if (n < 0x80) return Buffer.from([n]);
  const bytes: number[] = [];
  for (let v = n; v > 0; v >>= 8) bytes.unshift(v & 0xff);
  return Buffer.from([0x80 | bytes.length, ...bytes]);
}

function tlv(tag: number, content: Buffer): Buffer {
  return Buffer.concat([Buffer.from([tag]), derLength(content.length), content]);
}

const seq = (...parts: Buffer[]) => tlv(0x30, Buffer.concat(parts));
const set = (...parts: Buffer[]) => tlv(0x31, Buffer.concat(parts));
const utf8 = (s: string) => tlv(0x0c, Buffer.from(s, 'utf8'));
const printable = (s: string) => tlv(0x13, Buffer.from(s, 'ascii'));
const octetString = (b: Buffer) => tlv(0x04, b);
const integer = (n: number) => tlv(0x02, Buffer.from([n]));
const bitString = (b: Buffer) => tlv(0x03, Buffer.concat([Buffer.from([0]), b]));
/** Context-specific constructed tag [n] (explicit wrapping). */
const context = (n: number, content: Buffer) => tlv(0xa0 | n, content);

function oid(dotted: string): Buffer {
  const arcs = dotted.split('.').map(Number);
  const bytes: number[] = [arcs[0] * 40 + arcs[1]];
  for (const arc of arcs.slice(2)) {
    const chunk: number[] = [arc & 0x7f];
    for (let v = arc >> 7; v > 0; v >>= 7) chunk.unshift((v & 0x7f) | 0x80);
    bytes.push(...chunk);
  }
  return tlv(0x06, Buffer.from(bytes));
}

/** One RDN: SET { SEQUENCE { type, value } } — one attribute per SET. */
function rdn(typeOid: string, value: Buffer): Buffer {
  return set(seq(oid(typeOid), value));
}

// ---- validation ------------------------------------------------------------

/**
 * ISO 3166-1 alpha-2, current codes (plus the officially reserved 'XK'
 * for Kosovo, which several registries accept). Checking the SHAPE only
 * lets 'ZZ' — a code that exists nowhere — into a certificate request
 * that cannot be corrected after issuance.
 */
const ISO_3166_ALPHA2 = new Set(
  ('AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH ' +
    'BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL ' +
    'CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET ' +
    'FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU ' +
    'GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE ' +
    'KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC ' +
    'MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC ' +
    'NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT ' +
    'PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR ' +
    'SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA ' +
    'UG UM US UY UZ VA VC VE VG VI VN VU WF WS XK YE YT ZA ZM ZW').split(' '),
);

export function validateCsrConfig(config: CsrConfig): void {
  const required: Array<keyof CsrConfig> = [
    'commonName',
    'serialNumber',
    'organizationIdentifier',
    'organizationUnitName',
    'organizationName',
    'countryName',
    'invoiceType',
    'locationAddress',
    'industryBusinessCategory',
  ];
  for (const field of required) {
    if (typeof config[field] !== 'string' || config[field].length === 0) {
      throw new CsrConfigError(`${field} is required`);
    }
  }
  // EXACTLY three pipe-delimited components. `.+` for the last one would
  // swallow '|4-anything', letting a malformed EGS serial through — and
  // the serial is baked into the CSID, so it is not fixable after
  // onboarding.
  if (!/^1-[^|]+\|2-[^|]+\|3-[^|]+$/.test(config.serialNumber)) {
    throw new CsrConfigError(
      "serialNumber must be '1-<solution>|2-<model>|3-<uuid>'",
    );
  }
  if (!/^3\d{13}3$/.test(config.organizationIdentifier)) {
    throw new CsrConfigError(
      'organizationIdentifier must be a 15-digit VAT number starting and ending with 3',
    );
  }
  // TSCZ functionality map: T=standard(B2B), S=simplified(B2C); the last
  // two positions are RESERVED and must stay '00' — ZATCA's technical
  // guideline defines only 1000/0100/1100 as valid today, and a CSR with
  // anything else risks rejection at onboarding.
  if (!/^(10|01|11)00$/.test(config.invoiceType)) {
    throw new CsrConfigError(
      "invoiceType must be '1000' (standard), '0100' (simplified) or '1100' (both) — last two digits are reserved zeros",
    );
  }
  if (!ISO_3166_ALPHA2.has(config.countryName)) {
    throw new CsrConfigError(
      `countryName must be a real ISO 3166-1 alpha-2 code like SA, got ` +
        `'${config.countryName}'`,
    );
  }
  // ZATCA rule for VAT GROUP members: the organizational unit must carry
  // the group member's own 10-digit TIN, not a free-text branch name.
  // Membership IS derivable — the 11th digit of the VAT number is '1'
  // for a group registration (ZATCA's CSR field table). An earlier
  // version made this an opt-in flag, so the rule only applied when the
  // caller already knew about it; the flag now only ADDS to the derived
  // answer, and a group EGS can no longer be onboarded with a branch
  // name in OU by forgetting it.
  const isVatGroup =
    config.vatGroup === true || config.organizationIdentifier[10] === '1';
  if (isVatGroup && !/^\d{10}$/.test(config.organizationUnitName)) {
    throw new CsrConfigError(
      'organizationUnitName must be the 10-digit TIN of the VAT-group ' +
        `member when vatGroup is set, got '${config.organizationUnitName}'`,
    );
  }
}

// ---- generation ------------------------------------------------------------

export function generateCsr(
  config: CsrConfig,
  environment: ZatcaEnvironment = 'sandbox',
): GeneratedCsr {
  validateCsrConfig(config);

  const { privateKey, publicKey } = generateKeyPairSync('ec', {
    namedCurve: 'secp256k1',
  });
  // SPKI DER = SEQ{ SEQ{ id-ecPublicKey, secp256k1 }, BIT STRING <04|X|Y> } —
  // exactly the shape the reference CSR carries (uncompressed point).
  const spki = publicKey.export({ type: 'spki', format: 'der' });

  const subject = seq(
    rdn(OID.countryName, printable(config.countryName)),
    rdn(OID.organizationalUnitName, utf8(config.organizationUnitName)),
    rdn(OID.organizationName, utf8(config.organizationName)),
    rdn(OID.commonName, utf8(config.commonName)),
  );

  // subjectAltName = GeneralNames{ [4] directoryName } — [4] wraps the Name
  // explicitly (Name is a CHOICE), and each SAN attribute is its own RDN.
  const sanName = seq(
    rdn(OID.surname, utf8(config.serialNumber)),
    rdn(OID.uid, utf8(config.organizationIdentifier)),
    rdn(OID.title, utf8(config.invoiceType)),
    rdn(OID.registeredAddress, utf8(config.locationAddress)),
    rdn(OID.businessCategory, utf8(config.industryBusinessCategory)),
  );
  const san = seq(context(4, sanName));

  const extensions = seq(
    seq(
      oid(OID.certificateTemplateName),
      octetString(utf8(CERTIFICATE_TEMPLATE_BY_ENV[environment])),
    ),
    seq(oid(OID.subjectAltName), octetString(san)),
  );

  // attributes [0] IMPLICIT SET OF Attribute — the context tag REPLACES the
  // SET tag, so the Attribute sequence sits directly inside [0].
  const attributes = context(
    0,
    seq(oid(OID.extensionRequest), set(extensions)),
  );

  const certificationRequestInfo = seq(
    integer(0), // version: 1 (0x0)
    subject,
    spki,
    attributes,
  );

  // ECDSA-SHA256 over the CertificationRequestInfo DER; node emits the
  // signature DER-encoded, which is what the BIT STRING carries.
  const signature = createSign('SHA256')
    .update(certificationRequestInfo)
    .sign(privateKey);

  const csrDer = seq(
    certificationRequestInfo,
    seq(oid(OID.ecdsaWithSha256)),
    bitString(signature),
  );

  const csrPem = toPem('CERTIFICATE REQUEST', csrDer);
  return {
    csrPem,
    csrBase64: Buffer.from(csrPem).toString('base64'),
    privateKeyPem: privateKey
      .export({ type: 'sec1', format: 'pem' })
      .toString(),
    publicKeyPem: publicKey.export({ type: 'spki', format: 'pem' }).toString(),
  };
}

function toPem(label: string, der: Buffer): string {
  const b64 = der.toString('base64');
  const lines = b64.match(/.{1,64}/g) ?? [];
  return `-----BEGIN ${label}-----\n${lines.join('\n')}\n-----END ${label}-----\n`;
}
