import { createVerify } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  CERTIFICATE_TEMPLATE_BY_ENV,
  CsrConfig,
  CsrConfigError,
  generateCsr,
} from './csr';

/**
 * The CSR layout is locked against a reference CSR generated by ZATCA's own
 * SDK CLI and decoded with openssl asn1parse. The structural assertions here
 * are the offline half; when openssl exists on the host the last test has
 * openssl itself parse AND verify the CSR (CI's ubuntu always has it).
 */
const config: CsrConfig = {
  commonName: 'TST-886431145-399999999900003',
  serialNumber: '1-POS|2-A920|3-ed22f1d8-e6a2-1118-9b58-d9a8f11e445f',
  organizationIdentifier: '399999999900003',
  organizationUnitName: 'Riyadh Branch',
  organizationName: 'Maximum Speed Tech Supply LTD',
  countryName: 'SA',
  invoiceType: '0100',
  locationAddress: 'RRRD2929',
  industryBusinessCategory: 'Supply activities',
};

/** Minimal DER TLV reader — enough to split the CSR into its three parts. */
function readTlv(buf: Buffer, offset: number): { start: number; end: number; content: Buffer; tag: number } {
  const tag = buf[offset];
  let len = buf[offset + 1];
  let headerLen = 2;
  if (len & 0x80) {
    const n = len & 0x7f;
    len = 0;
    for (let i = 0; i < n; i++) len = (len << 8) | buf[offset + 2 + i];
    headerLen = 2 + n;
  }
  return {
    tag,
    start: offset,
    end: offset + headerLen + len,
    content: buf.subarray(offset + headerLen, offset + headerLen + len),
  };
}

function derFromPem(pem: string): Buffer {
  return Buffer.from(pem.replace(/-----[^-]+-----|\s/g, ''), 'base64');
}

describe('generateCsr', () => {
  const generated = generateCsr(config);
  const der = derFromPem(generated.csrPem);

  it('emits a PEM CSR and the base64-of-PEM body POST /compliance wants', () => {
    expect(generated.csrPem).toMatch(/^-----BEGIN CERTIFICATE REQUEST-----\n/);
    expect(generated.csrPem).toMatch(/-----END CERTIFICATE REQUEST-----\n$/);
    expect(Buffer.from(generated.csrBase64, 'base64').toString()).toBe(
      generated.csrPem,
    );
    expect(generated.privateKeyPem).toContain('BEGIN EC PRIVATE KEY');
  });

  it('signs the CertificationRequestInfo with the generated secp256k1 key', () => {
    const outer = readTlv(der, 0);
    // CRI is the outer SEQUENCE's first child.
    const cri = readTlv(der, outer.end - outer.content.length);
    const criBytes = der.subarray(cri.start, cri.end);
    const sigAlg = readTlv(der, cri.end);
    const sigBits = readTlv(der, sigAlg.end);
    // BIT STRING: first content byte = unused-bit count, rest = DER ECDSA sig.
    const signature = sigBits.content.subarray(1);

    expect(
      createVerify('SHA256')
        .update(criBytes)
        .verify(generated.publicKeyPem, signature),
    ).toBe(true);
  });

  it('carries the ZATCA EGS structure the SDK reference CSR has', () => {
    const hex = der.toString('hex');
    // certificateTemplateName 1.3.6.1.4.1.311.20.2
    expect(hex).toContain('06092b0601040182371402');
    // subjectAltName 2.5.29.17
    expect(hex).toContain('0603551d11');
    // UID 0.9.2342.19200300.100.1.1 (the VAT number's attribute)
    expect(hex).toContain('060a0992268993f22c640101');
    // EGS serial in SURNAME (2.5.4.4) — openssl's 'SN', NOT serialNumber
    // (2.5.4.5). The SDK's own CSR uses surname; 2.5.4.5 gets rejected.
    expect(hex).toContain(
      '06035504040c' + // 2.5.4.4 + UTF8String tag
        config.serialNumber.length.toString(16).padStart(2, '0') +
        Buffer.from(config.serialNumber).toString('hex'),
    );
    expect(hex).not.toContain('0603550405'); // no serialNumber attr anywhere
    // secp256k1 curve parameter
    expect(hex).toContain('06052b8104000a');
    // sandbox template name, as a UTF8String inside the extension
    expect(der.includes(Buffer.from('TSTZATCA-Code-Signing'))).toBe(true);
    // country is PrintableString 'SA' (the one non-UTF8 subject attr)
    expect(hex).toContain('06035504061302' + Buffer.from('SA').toString('hex'));
  });

  it('subject order matches the SDK reference: C, OU, O, CN', () => {
    const hex = der.toString('hex');
    const posC = hex.indexOf('0603550406');
    const posOU = hex.indexOf('060355040b');
    const posO = hex.indexOf('060355040a');
    const posCN = hex.indexOf('0603550403');
    expect(posC).toBeGreaterThan(-1);
    expect(posC).toBeLessThan(posOU);
    expect(posOU).toBeLessThan(posO);
    expect(posO).toBeLessThan(posCN);
  });

  it.each([
    ['sandbox', 'TSTZATCA-Code-Signing'],
    ['simulation', 'PREZATCA-Code-Signing'],
    ['production', 'ZATCA-Code-Signing'],
  ] as const)('%s environment stamps template %s', (env, template) => {
    expect(CERTIFICATE_TEMPLATE_BY_ENV[env]).toBe(template);
    const envDer = derFromPem(generateCsr(config, env).csrPem);
    expect(envDer.includes(Buffer.from(template))).toBe(true);
  });

  it.each([
    ['organizationIdentifier not 15 digits', { organizationIdentifier: '39999' }],
    ['organizationIdentifier not ending in 3', { organizationIdentifier: '399999999900001' }],
    ['organizationIdentifier not starting with 3', { organizationIdentifier: '199999999900003' }],
    ['invoiceType all zeros', { invoiceType: '0000' }],
    ['invoiceType wrong alphabet', { invoiceType: '12a0' }],
    // TSCZ last two positions are RESERVED zeros — '0111'/'1010' etc.
    // produce CSRs ZATCA can reject at onboarding.
    ['invoiceType reserved digit set', { invoiceType: '0111' }],
    ['invoiceType reserved digit set 2', { invoiceType: '1010' }],
    ['serialNumber missing the 1-|2-|3- shape', { serialNumber: 'PAX-A920' }],
    // A trailing `.+` used to swallow extra pipe components — the serial
    // is baked into the CSID, so a malformed one is unfixable later.
    [
      'serialNumber with a fourth component',
      { serialNumber: '1-POS|2-A920|3-unit-id|4-extra' },
    ],
    [
      'serialNumber with an empty component',
      { serialNumber: '1-POS|2-|3-unit-id' },
    ],
    ['countryName not ISO2', { countryName: 'KSA' }],
    // Shape-only validation accepted any two capitals, including codes
    // that exist nowhere — baked into a certificate that cannot be fixed.
    ['countryName ZZ (not a real country)', { countryName: 'ZZ' }],
    ['countryName XX (user-assigned, not ISO)', { countryName: 'XX' }],
    ['countryName lowercase', { countryName: 'sa' }],
    // VAT-GROUP members must carry the member's own 10-digit TIN in OU.
    [
      'vatGroup with a free-text organizational unit',
      { vatGroup: true, organizationUnitName: 'Main Branch' },
    ],
    [
      'vatGroup with a 9-digit TIN',
      { vatGroup: true, organizationUnitName: '123456789' },
    ],
    ['empty required field', { organizationName: '' }],
  ])('rejects %s', (_name, patch) => {
    expect(() => generateCsr({ ...config, ...patch })).toThrow(CsrConfigError);
  });

  it('accepts a VAT-group EGS whose OU is the member 10-digit TIN', () => {
    expect(() =>
      generateCsr({
        ...config,
        vatGroup: true,
        organizationUnitName: '3001234567',
      }),
    ).not.toThrow();
  });

  it('accepts real ISO country codes other than SA', () => {
    for (const countryName of ['AE', 'EG', 'GB', 'JO']) {
      expect(() => generateCsr({ ...config, countryName })).not.toThrow();
    }
  });

  // openssl parse+verify — definitive but host-dependent: always present on
  // CI's ubuntu, present on dev machines via Git; skipped elsewhere.
  const hasOpenssl = spawnSync('openssl', ['version']).status === 0;
  (hasOpenssl ? it : it.skip)('parses and verifies with openssl req', () => {
    const dir = mkdtempSync(join(tmpdir(), 'zatca-csr-'));
    try {
      const file = join(dir, 'test.csr');
      writeFileSync(file, generated.csrPem);
      const res = spawnSync('openssl', [
        'req',
        '-in',
        file,
        '-noout',
        '-text',
        '-verify',
      ]);
      expect(res.status).toBe(0);
      // OpenSSL 3.x prints name attrs as "C = SA", 1.1 as "C=SA" (Git for
      // Windows ships 1.1; CI's ubuntu ships 3.x). Normalize before
      // asserting so the same expectations hold on both.
      const text = res.stdout.toString().replace(/ = /g, '=');
      expect(text).toContain('secp256k1');
      expect(text).toContain('TSTZATCA-Code-Signing');
      expect(text).toContain(`SN=${config.serialNumber}`);
      expect(text).toContain('UID=399999999900003');
      expect(text).toContain('title=0100');
      expect(text).toContain('registeredAddress=RRRD2929');
      expect(text).toContain('businessCategory=Supply activities');
      expect(text).toContain(
        'C=SA, OU=Riyadh Branch, O=Maximum Speed Tech Supply LTD',
      );
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
